spring:
  datasource:
    url: jdbc:h2:file:./data/kzm-db;AUTO_SERVER=TRUE
    username:
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
        enabled: true
  sql:
    init:
      mode: always
      schema-locations: classpath:/schema.sql